### ISSUE TITLE
Eclipse Neon: Clone works, Clone&Import is not working: GIT default repository folder is ignored

### ISSUE THREAD

**Issue by MicBag** [baloise/egitblit#31]
This issue applies to Eclipse NEON (MS-Windows 7): 

Please, browse through the list of your avail groups / repos and select one for cloning:

If you're just use the **Clone** option, the default repository folder, specified in the git properties of Eclipse, will be used (that's correct).

If you're using the option **Clone & Import** option, the default repo folder of GIT will be **ignored**. The project will be cloned to your personal folder (on Windows 7) and not like expected to the git default repo folder.

btw: Maybe this is caused by a egit "feature". Because the clone & import code is reading the egit preference(-store) settings, to ask for the git default repo location.  

Cheers....

**Comment by MicBag** [comment]
Solution: 
Using org.eclipse.egit.core.RepositoryUtil.getDefaultRepositoryDir() instead of reading PreferenceStore at method com.baloise.egitblit.view.action.getWorkdir().

But this requires a actual version of eGit (e.g 4.4.1 - Don´t know when RepositoryUtils have been created. However, I will set required version of eGit to that version as well. I will push this fix soon.

**Comment by culmat** [comment]
Merci. :-)

**Comment by MicBag** [comment]
Hi Mr. Coolman,

ich glaube der Auto-Build / Deploy auf Eclipse läuft nicht. Habe die neue Version nicht automatisch bekommen.
Musst Du ihn manuell anstossen oder gab es einen Fehler beim Build? 

...oder habe ich vergessen irgendwo eine Version hochzusetzen damit der Mechanismus greift?
(Hab schon lange nichts mehr auf der Plattform deployed )

Cheers....
Michael

**Comment by baopso** [comment]
HI Michi
Das oauth token war ungültig habe es korrigiert :
https://github.com/baloise/egitblit/commit/4f4ada8e13700aec83f819914de1ef8dbdcd6da5 <https://github.com/baloise/egitblit/commit/4f4ada8e13700aec83f819914de1ef8dbdcd6da5>
jetzt ist er durchgelaufen:
https://travis-ci.org/baloise/egitblit/builds/166196270 <https://travis-ci.org/baloise/egitblit/builds/166196270>
Gruss
Matthias
